### ISSUE TITLE
Random error after some time, connection to http port

### ISSUE THREAD

**Issue by marvin-bitterlich** [inertia186/radiator#2]
No idea what caused this as of now...

Error:

```
Jun 30 10:37:09 minnowbooster app/worker.1: W, [2017-06-30T17:37:08.834818 #4]  WARN -- : Unable to perform request: #<Net::HTTP::Post:0x0000000479df70> :: too many connection resets (due to Net::ReadTimeout - Net::ReadTimeout) after 0 requests on 70338215773620, last used 1498844228.834622 seconds ago: ["/app/vendor/ruby-2.4.1/lib/ruby/2.4.0/net/protocol.rb:176:in `rbuf_fill'", "/app/vendor/ruby-2.4.1/lib/ruby/2.4.0/net/protocol.rb:154:in `readuntil'", "/app/vendor/ruby-2.4.1/lib/ruby/2.4.0/net/protocol.rb:164:in `readline'", "/app/vendor/ruby-2.4.1/lib/ruby/2.4.0/net/http/response.rb:40:in `read_status_line'", "/app/vendor/ruby-2.4.1/lib/ruby/2.4.0/net/http/response.rb:29:in `read_new'", "/app/vendor/ruby-2.4.1/lib/ruby/2.4.0/net/http.rb:1446:in `block in transport_request'", "/app/vendor/ruby-2.4.1/lib/ruby/2.4.0/net/http.rb:1443:in `catch'", "/app/vendor/ruby-2.4.1/lib/ruby/2.4.0/net/http.rb:1443:in `transport_request'", "/app/vendor/ruby-2.4.1/lib/ruby/2.4.0/net/http.rb:1416:in `request'", "/app/vendor/bundle/ruby/2.4.0/gems/scout_apm-2.1.26/lib/scout_apm/instruments/net_http.rb:26:in `block in request_with_scout_instruments'", "/app/vendor/bundle/ruby/2.4.0/gems/scout_apm-2.1.26/lib/scout_apm/tracer.rb:35:in `instrument'", "/app/vendor/bundle/ruby/2.4.0/gems/scout_apm-2.1.26/lib/scout_apm/instruments/net_http.rb:25:in `request_with_scout_instruments'", "/app/vendor/bundle/ruby/2.4.0/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:999:in `request'", "/app/vendor/bundle/ruby/2.4.0/gems/radiator-0.2.2/lib/radiator/api.rb:160:in `request'", "/app/vendor/bundle/ruby/2.4.0/gems/radiator-0.2.2/lib/radiator/api.rb:111:in `method_missing'", "/app/app/jobs/process_block_job.rb:26:in `perform'", "/app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.2/lib/active_job/execution.rb:37:in `block in perform_now'", "/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/callbacks.rb:108:in `block in run_callbacks'", "/app/vendor/bundle/ruby/2.4.0/gems/i18n-0.8.4/lib/i18n.rb:257:in `with_locale'", "/app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.2/lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'", "/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/callbacks.rb:117:in `instance_exec'", "/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/callbacks.rb:117:in `block in run_callbacks'", "/app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.2/lib/active_job/logging.rb:24:in `block (4 levels) in <module:Logging>'", "/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/notifications.rb:166:in `block in instrument'", "/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'", "/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/notifications.rb:166:in `instrument'", "/app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.2/lib/active_job/logging.rb:23:in `block (3 levels) in <module:Logging>'", "/app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.2/lib/active_job/logging.rb:46:in `tag_logger'", "/app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.2/lib/active_job/logging.rb:20:in `block (2 levels) in <module:Logging>'", "/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/callbacks.rb:117:in `instance_exec'", "/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/callbacks.rb:117:in `block in run_callbacks'", "/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/callbacks.rb:135:in `run_callbacks'", "/app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.2/lib/active_job/execution.rb:33:in `perform_now'", "/app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.2/lib/active_job/execution.rb:22:in `block in execute'", "/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/callbacks.rb:108:in `block in run_callbacks'", "/app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.2/lib/active_job/railtie.rb:26:in `block (4 levels) in <class:Railtie>'", "/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/execution_wrapper.rb:85:in `wrap'", "/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/reloader.rb:68:in `block in wrap'", "/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/execution_wrapper.rb:81:in `wrap'", "/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/reloader.rb:67:in `wrap'", "/app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.2/lib/active_job/railtie.rb:25:in `block (3 levels) in <class:Railtie>'", "/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/callbacks.rb:117:in `instance_exec'", "/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/callbacks.rb:117:in `block in run_callbacks'", "/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/callbacks.rb:135:in `run_callbacks'", "/app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.2/lib/active_job/execution.rb:20:in `execute'", "/app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.2/lib/active_job/queue_adapters/sidekiq_adapter.rb:40:in `perform'", "/app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:199:in `execute_job'", "/app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:170:in `block (2 levels) in process'", "/app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'", "/app/vendor/bundle/ruby/2.4.0/gems/scout_apm-2.1.26/lib/scout_apm/background_job_integrations/sidekiq.rb:71:in `call'", "/app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'", "/app/vendor/bundle/ruby/2.4.0/gems/sidekiq-unique-jobs-5.0.8/lib/sidekiq_unique_jobs/lock/while_executing.rb:43:in `block in execute'", "/app/vendor/bundle/ruby/2.4.0/gems/sidekiq-unique-jobs-5.0.8/lib/sidekiq_unique_jobs/lock/while_executing.rb:22:in `synchronize'", "/app/vendor/bundle/ruby/2.4.0/gems/sidekiq-unique-jobs-5.0.8/lib/sidekiq_unique_jobs/lock/while_executing.rb:42:in `execute'", "/app/vendor/bundle/ruby/2.4.0/gems/sidekiq-unique-jobs-5.0.8/lib/sidekiq_unique_jobs/server/middleware.rb:18:in `call'", "/app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'", "/app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/middleware/chain.rb:133:in `invoke'", "/app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:169:in `block in process'", "/app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:141:in `block (6 levels) in dispatch'", "/app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/job_retry.rb:97:in `local'", "/app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:140:in `block (5 levels) in dispatch'", "/app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/rails.rb:42:in `block in call'", "/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/execution_wrapper.rb:85:in `wrap'", "/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/reloader.rb:68:in `block in wrap'", "/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/execution_wrapper.rb:85:in `wrap'", "/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/reloader.rb:67:in `wrap'", "/app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/rails.rb:41:in `call'", "/app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:136:in `block (4 levels) in dispatch'", "/app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:215:in `stats'", "/app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:131:in `block (3 levels) in dispatch'", "/app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/job_logger.rb:7:in `call'", "/app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:130:in `block (2 levels) in dispatch'", "/app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/job_retry.rb:72:in `global'", "/app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:129:in `block in dispatch'", "/app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/logging.rb:44:in `with_context'", "/app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/logging.rb:38:in `with_job_hash_context'", "/app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:128:in `dispatch'", "/app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:168:in `process'", "/app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:85:in `process_one'", "/app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:73:in `run'", "/app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/util.rb:16:in `watchdog'", "/app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/util.rb:25:in `block in safe_thread'"] 
Jun 30 10:37:09 minnowbooster app/worker.1: E, [2017-06-30T17:37:09.076331 #4] ERROR -- : Error performing ProcessBlockJob (Job ID: 5144d2ef-59e8-4360-bb8e-333e74a44437) from Sidekiq(default) in 34175.53ms: JSON::ParserError (784: unexpected token at '<html>  
Jun 30 10:37:09 minnowbooster app/worker.1: <head><title>400 The plain HTTP request was sent to HTTPS port</title></head>  
Jun 30 10:37:09 minnowbooster app/worker.1: <body bgcolor="white">  
Jun 30 10:37:09 minnowbooster app/worker.1: <center><h1>400 Bad Request</h1></center>  
Jun 30 10:37:09 minnowbooster app/worker.1: <center>The plain HTTP request was sent to HTTPS port</center>  
Jun 30 10:37:09 minnowbooster app/worker.1: </body>  
Jun 30 10:37:09 minnowbooster app/worker.1: </html>  
Jun 30 10:37:09 minnowbooster app/worker.1: '): 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/json-1.8.6/lib/json/common.rb:155:in `parse' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/json-1.8.6/lib/json/common.rb:155:in `parse' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/json-1.8.6/lib/json/common.rb:14:in `[]' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/radiator-0.2.2/lib/radiator/api.rb:114:in `method_missing' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/app/jobs/process_block_job.rb:26:in `perform' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.2/lib/active_job/execution.rb:37:in `block in perform_now' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/callbacks.rb:108:in `block in run_callbacks' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/i18n-0.8.4/lib/i18n.rb:257:in `with_locale' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.2/lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/callbacks.rb:117:in `instance_exec' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/callbacks.rb:117:in `block in run_callbacks' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.2/lib/active_job/logging.rb:24:in `block (4 levels) in <module:Logging>' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/notifications.rb:166:in `block in instrument' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/notifications/instrumenter.rb:21:in `instrument' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/notifications.rb:166:in `instrument' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.2/lib/active_job/logging.rb:23:in `block (3 levels) in <module:Logging>' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.2/lib/active_job/logging.rb:46:in `tag_logger' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.2/lib/active_job/logging.rb:20:in `block (2 levels) in <module:Logging>' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/callbacks.rb:117:in `instance_exec' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/callbacks.rb:117:in `block in run_callbacks' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/callbacks.rb:135:in `run_callbacks' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.2/lib/active_job/execution.rb:33:in `perform_now' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.2/lib/active_job/execution.rb:22:in `block in execute' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/callbacks.rb:108:in `block in run_callbacks' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.2/lib/active_job/railtie.rb:26:in `block (4 levels) in <class:Railtie>' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/execution_wrapper.rb:85:in `wrap' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/reloader.rb:68:in `block in wrap' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/execution_wrapper.rb:81:in `wrap' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/reloader.rb:67:in `wrap' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.2/lib/active_job/railtie.rb:25:in `block (3 levels) in <class:Railtie>' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/callbacks.rb:117:in `instance_exec' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/callbacks.rb:117:in `block in run_callbacks' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/callbacks.rb:135:in `run_callbacks' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.2/lib/active_job/execution.rb:20:in `execute' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.2/lib/active_job/queue_adapters/sidekiq_adapter.rb:40:in `perform' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:199:in `execute_job' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:170:in `block (2 levels) in process' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/middleware/chain.rb:128:in `block in invoke' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/scout_apm-2.1.26/lib/scout_apm/background_job_integrations/sidekiq.rb:71:in `call' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/middleware/chain.rb:130:in `block in invoke' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-unique-jobs-5.0.8/lib/sidekiq_unique_jobs/lock/while_executing.rb:43:in `block in execute' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-unique-jobs-5.0.8/lib/sidekiq_unique_jobs/lock/while_executing.rb:22:in `synchronize' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-unique-jobs-5.0.8/lib/sidekiq_unique_jobs/lock/while_executing.rb:42:in `execute' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-unique-jobs-5.0.8/lib/sidekiq_unique_jobs/server/middleware.rb:18:in `call' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/middleware/chain.rb:130:in `block in invoke' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/middleware/chain.rb:133:in `invoke' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:169:in `block in process' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:141:in `block (6 levels) in dispatch' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/job_retry.rb:97:in `local' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:140:in `block (5 levels) in dispatch' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/rails.rb:42:in `block in call' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/execution_wrapper.rb:85:in `wrap' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/reloader.rb:68:in `block in wrap' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/execution_wrapper.rb:85:in `wrap' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/reloader.rb:67:in `wrap' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/rails.rb:41:in `call' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:136:in `block (4 levels) in dispatch' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:215:in `stats' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:131:in `block (3 levels) in dispatch' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/job_logger.rb:7:in `call' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:130:in `block (2 levels) in dispatch' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/job_retry.rb:72:in `global' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:129:in `block in dispatch' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/logging.rb:44:in `with_context' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/logging.rb:38:in `with_job_hash_context' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:128:in `dispatch' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:168:in `process' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:85:in `process_one' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/processor.rb:73:in `run' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/util.rb:16:in `watchdog' 
Jun 30 10:37:09 minnowbooster app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.0.3/lib/sidekiq/util.rb:25:in `block in safe_thread' 
Jun 30 10:37:09 minnowbooster app/worker.1: API derped with 784: unexpected token at '<html>  
Jun 30 10:37:09 minnowbooster app/worker.1: <head><title>400 The plain HTTP request was sent to HTTPS port</title></head>  
Jun 30 10:37:09 minnowbooster app/worker.1: <body bgcolor="white">  
Jun 30 10:37:09 minnowbooster app/worker.1: <center><h1>400 Bad Request</h1></center>  
Jun 30 10:37:09 minnowbooster app/worker.1: <center>The plain HTTP request was sent to HTTPS port</center>  
Jun 30 10:37:09 minnowbooster app/worker.1: </body>  
Jun 30 10:37:09 minnowbooster app/worker.1: </html>  
Jun 30 10:37:09 minnowbooster app/worker.1: ' 
```

**Comment by marvin-bitterlich** [comment]
Should be fixed with new error handling
