### ISSUE TITLE
undefined method `strip' for

### ISSUE THREAD

**Issue by krischik** [inertia186/radiator#31]
When performing an `claim_reward_balance` I get the following error:

```log
	14: from /usr/local/lib/ruby/gems/2.7.0/gems/radiator-0.4.7/lib/radiator/chain.rb:242:in `broadcast!'
	13: from /usr/local/lib/ruby/gems/2.7.0/gems/radiator-0.4.7/lib/radiator/transaction.rb:99:in `process'
	12: from /usr/local/lib/ruby/gems/2.7.0/gems/radiator-0.4.7/lib/radiator/transaction.rb:99:in `loop'
	11: from /usr/local/lib/ruby/gems/2.7.0/gems/radiator-0.4.7/lib/radiator/transaction.rb:100:in `block in process'
	10: from /usr/local/lib/ruby/gems/2.7.0/gems/radiator-0.4.7/lib/radiator/transaction.rb:177:in `payload'
	 9: from /usr/local/lib/ruby/gems/2.7.0/gems/radiator-0.4.7/lib/radiator/transaction.rb:122:in `operations'
	 8: from /usr/local/lib/ruby/gems/2.7.0/gems/radiator-0.4.7/lib/radiator/transaction.rb:122:in `map'
	 7: from /usr/local/lib/ruby/gems/2.7.0/gems/radiator-0.4.7/lib/radiator/transaction.rb:125:in `block in operations'
	 6: from /usr/local/lib/ruby/gems/2.7.0/gems/radiator-0.4.7/lib/radiator/transaction.rb:125:in `new'
	 5: from /usr/local/lib/ruby/gems/2.7.0/gems/radiator-0.4.7/lib/radiator/operation.rb:11:in `initialize'
	 4: from /usr/local/lib/ruby/gems/2.7.0/gems/radiator-0.4.7/lib/radiator/operation.rb:11:in `each'
	 3: from /usr/local/lib/ruby/gems/2.7.0/gems/radiator-0.4.7/lib/radiator/operation.rb:12:in `block in initialize'
	 2: from /usr/local/lib/ruby/gems/2.7.0/gems/radiator-0.4.7/lib/radiator/operation_types.rb:136:in `type'
	 1: from /usr/local/lib/ruby/gems/2.7.0/gems/radiator-0.4.7/lib/radiator/operation_types.rb:136:in `new'
/usr/local/lib/ruby/gems/2.7.0/gems/radiator-0.4.7/lib/radiator/type/amount.rb:22:in `initialize': undefined method `strip' for #<Radiator::Type::Amount:0x00007faaf5123cc8> (NoMethodError)
```

According to `operation_types.rb` the operation `claim_reward_balance` is defined to take `Type::Amount`:

```ruby
      claim_reward_balance: {
        reward_steem: Type::Amount,
        reward_sbd: Type::Amount,
        reward_vests: Type::Amount
      },
```

Could it be that Type::Amount is missing a copy constructor option?

**Comment by inertia186** [comment]
`Radiator::Type::Amount` will be deprecated in favor of `Hive::Type::Amount` (by default).
