### ISSUE TITLE
FrozenError

### ISSUE THREAD

**Issue by ShadowMyst** [inertia186/radiator#35]
I was using hive-ruby (since it came out of the gem here, but the same thing happened to me with radiator.

Following your documentation I get this error
can't modify frozen #<Class:#<Class:0x00007faea44687c8>

using
```
Hive::Broadcast.vote(wif: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', params: parameters) do |result|
            puts result
  end
```
But as much as I have looked for it I don't know where my error is.

**Comment by inertia186** [comment]
Maybe try `params: parameters.dup`

**Comment by ShadowMyst** [comment]
I keep getting the same error
```

/home/shadowmyst/.rvm/gems/ruby-3.1.1/gems/hive-ruby-1.0.3/lib/hive/api.rb:46:in `api_name=': can't modify frozen #<Class:#<Class:0x00007f6efbc2ea18>>: #<Class:0x00007f6efbc2ea18> (FrozenError)
        from /home/shadowmyst/.rvm/gems/ruby-3.1.1/gems/hive-ruby-1.0.3/lib/hive.rb:88:in `const_missing'
        from /home/shadowmyst/.rvm/gems/ruby-3.1.1/gems/hive-ruby-1.0.3/lib/hive/transaction_builder.rb:46:in `initialize'
        from /home/shadowmyst/.rvm/gems/ruby-3.1.1/gems/hive-ruby-1.0.3/lib/hive/broadcast.rb:1367:in `new'
        from /home/shadowmyst/.rvm/gems/ruby-3.1.1/gems/hive-ruby-1.0.3/lib/hive/broadcast.rb:1367:in `process'
        from /home/shadowmyst/.rvm/gems/ruby-3.1.1/gems/hive-ruby-1.0.3/lib/hive/broadcast.rb:70:in `vote'
        from voter.rb:10:in `<main>'

```

**Comment by inertia186** [comment]
Ok, it must be a ruby-3 thing.  If you can try it on ruby-2.7, I bet it'll work better.

**Comment by ShadowMyst** [comment]
Oh yes, it works fine in ruby 2.7, too bad it doesn't work in ruby 3.1.1, I guess I'll have to try the library in JS :c
