### ISSUE TITLE
Error while backing off

### ISSUE THREAD

**Issue by marvin-bitterlich** [inertia186/radiator#7]
We sometimes get these errors:

```
Oct 13 18:03:56 d.a6905b7e-6d53-4d51-b6ad-24ce6adad21e app/worker.1: 4 TID-gfuv8 WARN: TypeError: can't convert nil into an exact number 
Oct 13 18:03:56 d.a6905b7e-6d53-4d51-b6ad-24ce6adad21e app/worker.1: 4 TID-gfuv8 WARN: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/core_ext/time/calculations.rb:267:in `-' 
Oct 13 18:03:56 d.a6905b7e-6d53-4d51-b6ad-24ce6adad21e app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/core_ext/time/calculations.rb:267:in `minus_with_duration' 
Oct 13 18:03:56 d.a6905b7e-6d53-4d51-b6ad-24ce6adad21e app/worker.1: /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/core_ext/time/calculations.rb:278:in `minus_with_coercion' 
Oct 13 18:03:56 d.a6905b7e-6d53-4d51-b6ad-24ce6adad21e app/worker.1: /app/vendor/bundle/ruby/2.4.0/bundler/gems/radiator-19acff96bf11/lib/radiator/api.rb:576:in `backoff' 
Oct 13 18:03:56 d.a6905b7e-6d53-4d51-b6ad-24ce6adad21e app/worker.1: /app/vendor/bundle/ruby/2.4.0/bundler/gems/radiator-19acff96bf11/lib/radiator/api.rb:443:in `block in method_missing' 
Oct 13 18:03:56 d.a6905b7e-6d53-4d51-b6ad-24ce6adad21e app/worker.1: /app/vendor/bundle/ruby/2.4.0/bundler/gems/radiator-19acff96bf11/lib/radiator/api.rb:359:in `loop' 
Oct 13 18:03:56 d.a6905b7e-6d53-4d51-b6ad-24ce6adad21e app/worker.1: /app/vendor/bundle/ruby/2.4.0/bundler/gems/radiator-19acff96bf11/lib/radiator/api.rb:359:in `method_missing' 
```

We call it like this:

```
  def self.get_post(username, permlink)
    api.get_content(username, permlink).result
  end
```

**Comment by inertia186** [comment]
Fixed in bcba68eae8c8f21210a36b49f3f4ade9164eaf20
